### ISSUE TITLE
Replace displayShortcutList() Dialog with Cheatsheet

### ISSUE THREAD

**Issue by latenitefilms** [CommandPost/CommandPost#63]
Something similar to [this](https://github.com/ashfinal/awesome-hammerspoon/blob/master/modes/cheatsheet.lua).

**Comment by latenitefilms** [comment]
Once everything is nicely controlled by the "command" plugin - we should be able to make this fairly easily I would think.

**Comment by latenitefilms** [comment]
Basically, I think this "cheat sheet" should list all of the Final Cut Pro menubar shortcuts (basically just reading them off `menumap.json` using the `cp.finalcutpro` api), as well as all the active CommandPost shortcuts (retrieved from `cp.commands`). This will allow users to press a shortcut key or press a menubar item to instantly and easily see a "cheat sheet" of all the CommandPost commands, as well as the Final Cut Pro menubar commands, which would be really handy (as I'm personally constantly forgetting what the default CommandPost shortcut keys are!).

**Comment by randomeizer** [comment]
Reading off menumap.json would always be in English, but I get what you're
saying.

I'm thinking of generating commands for the various menu items anyway,
since the HUD let's you assign menu items and the Console lets you activate
them also. Not sure if I would mix them in with the standard 'fcpx' command
group, or have a separate group.

**Comment by latenitefilms** [comment]
Ah yes, of course. Yes - we'd need it to display everything in the "local" language.

Yes, I figured you'd want to replace my `menuItemShortcut()` function, so was curious to see what you were going to do with it!

**Comment by latenitefilms** [comment]
We should probably tackle this once #306 is complete too.

**Comment by randomeizer** [comment]
Is it even necessary any more? It's visible in the preferences now...

**Comment by latenitefilms** [comment]
I don't think the **Display Keyboard Shortcuts** feature is necessary and can be removed. However, a "cheatsheet" like the original example, could be really cool - as it could display all of Final Cut Pro's shortcuts (or any app for that matter) as a quick reference.

**Comment by latenitefilms** [comment]
Cool idea, but probably not worth spending any time on.
