### ISSUE TITLE
Shortcut to go to full screen mode without playing

### ISSUE THREAD

**Issue by randomeizer** [CommandPost/CommandPost#7]

**Comment by latenitefilms** [comment]
I'm not sure this is actually possible.

**Comment by randomeizer** [comment]
Could hit spacebar after the full screen window opens?

**Comment by latenitefilms** [comment]
Yes, but it's not exactly frame accurate - and from memory, I think the person who wanted this feature basically just wanted a shortcut key to quickly view the current frame bigger (so they could check for things in shot, etc.). However, it might be possible to use the fullscreen playback navigation bar to work out how many frames we need to go back to get things in sync. I'll have a play sometime.

**Comment by randomeizer** [comment]
Ah, ok. Leave it open on the back burner then.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now.

**Comment by latenitefilms** [comment]
Also requested by Byk Valkonen [here](https://www.facebook.com/groups/commandpost/permalink/2368336383422059/?comment_id=2368692230053141).
